run_title: 'qartezator-pix2pix'

location:
  data_root_dir: qartezator/data/maps
  out_root_dir: /home/cognaize/Desktop/YSU/qartezator/qartezator/experiments/outputs

datamodule:
  root_path: ./data/maps
  train_txt_path: assets/train.txt
  val_txt_path: assets/val.txt
  test_txt_path: assets/test.txt
  train_batch_size: 16
  val_batch_size: 4
  test_batch_size: 4
  num_workers: 2
  input_size: 256
  pad_to_modulo: 32
  mean: null
  std: null

training_model:
  lr: 0.0002
  beta: 0.5
  batch_size: 16
  l1_lambda: 100
  max_epochs: 1000
  load_model: True
  save_model: True
  model_dir: 'trained_model'
  checkpoint_disc: 'trained_model/discriminator_model.pth'
  checkpoint_gen: 'trained_model/generator_model.pth'
